import {chromium} from '@playwright/test';
import {PNG} from 'pngjs';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';

const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--enable-webgl','--use-angle=d3d11']});
const output='test-results/continuous';
await mkdir(output,{recursive:true});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
page.on('pageerror',error=>errors.push(error.message));
const url='http://127.0.0.1:5188/';
const scrollTo=async selector=>{
  await page.locator(selector).evaluate(el=>el.scrollIntoView({behavior:'instant',block:'start'}));
  await page.waitForTimeout(250);
};
const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
try{
  await page.goto(url+'#home',{waitUntil:'networkidle'});
  assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('continuous-mode')),true);
  assert.equal(await page.locator('[data-panel][inert]').count(),0);
  assert.equal(await page.locator('main [data-panel]').count(),6);
  assert.equal(await page.locator('#commercial-intro').isVisible(),true);
  assert.ok(await page.locator('#commercial-intro').evaluate(el=>el.getBoundingClientRect().top<innerHeight),'next section should be hinted below the hero');
  await page.mouse.wheel(0,630);
  await page.waitForTimeout(320);
  assert.ok(await page.evaluate(()=>scrollY)>300,'wheel naturally advances through the document');
  await scrollTo('#commercial-intro');
  assert.ok(await page.locator('#commercial-title .story-line-text').first().evaluate(el=>el.classList.contains('is-visible')),'commercial headline enters with scroll');
  await page.keyboard.press('End');
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('body').getAttribute('data-active-panel'),'5','keyboard End reaches the footer');
  await page.keyboard.press('Home');
  await page.waitForTimeout(1100);
  assert.ok(await page.evaluate(()=>scrollY)<100,'keyboard Home returns to the top');
  await page.locator('.header a[href="#platform"]').click();
  await page.waitForTimeout(900);
  assert.equal(new URL(page.url()).hash,'#platform');
  assert.equal(await page.locator('body').getAttribute('data-active-panel'),'3');
  await page.goBack();
  await page.waitForTimeout(550);
  assert.ok(await page.evaluate(()=>scrollY)<1000,'history restores earlier reading position');
  await scrollTo('#perspective');
  const solution=page.locator('#solution-spatial');
  await solution.click();
  assert.equal(await solution.getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#solution-spatial-panel').isVisible(),true);
  await scrollTo('#platform');
  await page.locator('#tab-connect').click();
  assert.equal(await page.locator('#tab-connect').getAttribute('aria-selected'),'true');
  const pause=page.locator('#motion-toggle');
  await pause.click();
  assert.equal(await pause.getAttribute('aria-pressed'),'true');
  await pause.click();
  assert.equal(await pause.getAttribute('aria-pressed'),'false');
  await scrollTo('#inquiry');
  await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));
  await page.waitForTimeout(350);
  assert.equal(await page.locator('body').getAttribute('data-active-panel'),'5');
  assert.ok(await page.locator('.site-footer').isVisible());
  await page.locator('.footer-navigation [data-scroll-team]').click();
  await page.waitForTimeout(1300);
  assert.equal(new URL(page.url()).hash,'#inquiry-title');
  const headingTop=await page.locator('#inquiry-title').evaluate(el=>el.getBoundingClientRect().top);
  assert.ok(headingTop>30&&headingTop<180,`team link returns to the heading below the fixed header: ${headingTop}`);
  await page.locator('.footer-contact [data-contact]').click();
  assert.ok(await page.locator('#contact-dialog').isVisible());
  assert.match(await page.locator('#contact-dialog').innerText(),/不会发送或保存/);
  await page.locator('#contact-form input[name=name]').fill('Preview');
  await page.locator('#contact-form input[name=email]').fill('preview@example.test');
  await page.locator('#contact-form textarea[name=message]').fill('Test project brief');
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#contact-form button[type=submit]').click()]);
  assert.match(download.suggestedFilename(),/\.txt$/);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#contact-dialog').isVisible(),false);
  await page.locator('.footer-bottom a[href="#home"]').click();
  await page.waitForTimeout(1100);
  assert.equal(new URL(page.url()).hash,'#home');
  assert.ok(await page.evaluate(()=>scrollY)<100);

  for(const [width,height] of [[1920,1080],[1440,900],[1024,768],[390,844]]){
    await page.setViewportSize({width,height});
    await scrollTo('#home');
    await page.screenshot({path:`${output}/home-${width}.png`});
    await scrollTo('#commercial-intro');
    await page.screenshot({path:`${output}/business-${width}.png`});
    await scrollTo('#perspective');
    await page.screenshot({path:`${output}/solutions-${width}.png`});
    await scrollTo('#computation');
    await page.screenshot({path:`${output}/delivery-${width}.png`});
    await scrollTo('#platform');
    await page.screenshot({path:`${output}/technology-${width}.png`});
    await scrollTo('#inquiry');
    await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));
    await page.waitForTimeout(200);
    await page.screenshot({path:`${output}/footer-${width}.png`});
    assert.ok((await overflow())<=1,`${width}px has horizontal overflow`);
  }
  await page.setViewportSize({width:1440,height:900});
  await scrollTo('#home');
  await page.waitForTimeout(400);
  const canvasPath=`${output}/canvas.png`;
  await page.locator('#cell-scene').screenshot({path:canvasPath});
  const png=PNG.sync.read(await readFile(canvasPath));
  let nonblack=0;
  for(let i=0;i<png.data.length;i+=40){
    if(png.data[i]>35||png.data[i+1]>35||png.data[i+2]>35)nonblack++;
  }
  assert.ok(nonblack>png.data.length/40*.01,'3D canvas is visibly nonblank');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('body').getAttribute('data-motion'),'paused');
  await scrollTo('#inquiry');
  assert.ok(await page.locator('.collaboration-band').isVisible());
  assert.deepEqual(errors,[]);
  console.log('PASS: continuous scroll, business sections, navigation/history, controls, local draft, four viewports and 3D pixels');
}finally{await browser.close();}
